
[tasks.build]
run = """
go build -o bin/osv ./main.go
cp ./bin/osv $HOME/.local/bin/osv
"""

[tasks.build-all]
run = """
GOOS=linux GOARCH=amd64 go build -o dist/linux/amd64/osv ./main.go
GOOS=linux GOARCH=arm64 go build -o dist/linux/arm64/osv ./main.go
GOOS=windows GOARCH=amd64 go build -o dist/windows/amd64/osv.exe ./main.go
GOOS=windows GOARCH=arm64 go build -o dist/windows/arm64/osv.exe ./main.go
GOOS=darwin GOARCH=amd64 go build -o dist/darwin/amd64/osv ./main.go
GOOS=darwin GOARCH=arm64 go build -o dist/darwin/arm64/osv ./main.go
"""

[tasks.archive]
run = """
tar -czvf dist/osv-linux-amd64.tar.gz -C dist/linux/amd64 osv
tar -czvf dist/osv-linux-arm64.tar.gz -C dist/linux/arm64 osv
zip -j dist/osv-windows-amd64.zip dist/windows/amd64/osv.exe
zip -j dist/osv-windows-arm64.zip dist/windows/arm64/osv.exe
tar -czvf dist/osv-darwin-amd64.tar.gz -C dist/darwin/amd64 osv
tar -czvf dist/osv-darwin-arm64.tar.gz -C dist/darwin/arm64 osv
"""

